In [7]:
# Import Library
import pandas as pd

# Read in the data
businesses = pd.read_csv('data/businesses.csv')
new_businesses = pd.read_csv('data/new_businesses.csv')
countries = pd.read_csv('data/countries.csv')
categories = pd.read_csv('data/categories.csv')

In [5]:
# View the data
businesses.head()

                         business  year_founded category_code country_code
0                  Hamoud Boualem          1878         CAT11          DZA
1  Communauté Électrique du Bénin          1968         CAT10          BEN
2        Botswana Meat Commission          1965          CAT1          BWA
3                     Air Burkina          1967          CAT2          BFA
4                         Brarudi          1955          CAT9          BDI

In [8]:
new_businesses.head()

                    business  year_founded category_code country_code
0                 Fiji Times          1869         CAT13          FJI
1  J. Armando Bermúdez & Co.          1852          CAT9          DOM

In [9]:
countries.head()

  country_code               country continent
0          AFG           Afghanistan      Asia
1          AGO                Angola    Africa
2          ALB               Albania    Europe
3          AND               Andorra    Europe
4          ARE  United Arab Emirates      Asia

In [10]:
categories.head()

  category_code                   category
0          CAT1                Agriculture
1          CAT2       Aviation & Transport
2          CAT3          Banking & Finance
3          CAT4  Cafés, Restaurants & Bars
4          CAT5               Conglomerate

In [13]:
# What is the oldest business on every continent?

# Start merging data
businesses_countries = businesses.merge(countries, on='country_code')

# Create a new Dataframe that lists only the continent and oldest (min) year_found
continent = businesses_countries.groupby('continent').agg({'year_founded':'min'})

# Merge this continent Datatframe with business_countries
merged_continent = continent.merge(businesses_countries, on=['continent','year_founded'])

# Subset the continent Dataframe
oldest_business_continent = merged_continent[['continent','country','business','year_founded']]

# View the result
print(oldest_business_continent)

       continent    country                     business  year_founded
0         Africa  Mauritius               Mauritius Post          1772
1           Asia      Japan                   Kongō Gumi           578
2         Europe    Austria  St. Peter Stifts Kulinarium           803
3  North America     Mexico  La Casa de Moneda de México          1534
4        Oceania  Australia               Australia Post          1809
5  South America       Peru      Casa Nacional de Moneda          1565

In [14]:
# How many countries per continent lack data on the oldest business

# Add the data in new_businesses to the existing businesses
all_businesses = pd.concat([new_businesses, businesses])

# Perform a new merge between the businesses and countries data
new_all_countries = all_businesses.merge(countries, on='country_code', how='outer', indicator=True)

# Filter to find countries with missing business data
new_missing_countries = new_all_countries[new_all_countries['_merge'] != 'both']

# Group by continent and create a 'count_missing' column
count_missing = new_missing_countries.groupby('continent').agg({'country':'count'})
count_missing.columns = ['count_missing']

# View the results
print(count_missing)

               count_missing
continent
Africa                     3
Asia                       7
Europe                     2
North America              5
Oceania                   10
South America              3

In [16]:
# Which business categories are best suited to last over the course of the centuries?

# Merge the businesses and categories data into one Dataframe
businesses_categories = businesses.merge(categories, on='category_code')

# Merge all businesses, countries, and categories together
businesses_categories_countries = businesses_categories.merge(countries, on='country_code')

# Create the oldest by continent and category Dataframe
oldest_by_continent_category = businesses_categories_countries.groupby(['continent', 'category']).agg({'year_founded':'min'})
oldest_by_continent_category.head()

                                             year_founded
continent category
Africa    Agriculture                                1947
          Aviation & Transport                       1854
          Banking & Finance                          1892
          Distillers, Vintners, & Breweries          1933
          Energy                                     1968